### ISSUE TITLE
Allow for "allowed domains" to be configurable

### ISSUE THREAD

**Issue by aaemnnosttv** [techanvil/chrysalis#1]
It would be nice if the allowed domains for Google sign in were not hard coded. How about a config file or even env var instead?

https://github.com/techanvil/chrysalis/blob/e554dc01001ca6f66d7f3d86faf6f19e413c4a13/src/auth.ts#L4-L9

**Comment by techanvil** [comment]
Thanks for the suggestion, @aaemnnosttv! `ALLOWED_DOMAINS` was a slightly last minute addition, it would definitely be nice for it to be configurable.

I've made it so, via the `CHRYSALIS_ALLOWED_DOMAINS` env var, an optional comma separated string of domains. It would be nice to use a more structured config, e.g. a YAML file, I'll take a look at that at some point (or, PRs welcome 😄).

I've tweaked the `MAX_ROUGH_CHAT_SESSION_SIZE` and `MAX_CHAT_SESSIONS` variables in the process too, prepending `CHRYSALIS_` to both of them - and also fixed a mistake in the README re. `MAX_CHAT_SESSIONS`, which was good to spot. So, a small but useful update, cheers!
